/**
 * Default Built-in RuTracker Scraper Categories
 * Central source of truth for all built-in platforms.
 */

const DEFAULT_CATEGORIES = [
  {
    id: "switch",
    name: "Nintendo Switch",
    group: "nintendo",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=1605",
    titleSearch: ["[Nintendo Switch]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "psx",
    name: "Playstation 1",
    group: "playstation",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=908",
    titleSearch: ["[PS]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "ps2",
    name: "Playstation 2",
    group: "playstation",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=357",
    titleSearch: ["[PS2]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "psp",
    name: "Playstation Portable",
    group: "playstation",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=1352",
    titleSearch: ["[PSP]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "ps3",
    name: "Playstation 3",
    group: "playstation",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=886",
    titleSearch: ["[PS3]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "ps4",
    name: "Playstation 4",
    group: "playstation",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=973",
    titleSearch: ["[PS4]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "ps5",
    name: "Playstation 5",
    group: "playstation",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=546",
    titleSearch: ["[PS5]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "psvita",
    name: "Playstation Vita",
    group: "playstation",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=595",
    titleSearch: ["[PS Vita]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "xbox",
    name: "Original Xbox",
    group: "xbox",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=887",
    titleSearch: ["Original Xbox", "XBOX", "Xbox"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "xbox360",
    name: "Xbox 360",
    group: "xbox",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=510",
    titleSearch: ["[XBOX360]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "wii",
    name: "Nintendo Wii",
    group: "nintendo",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=773",
    titleSearch: ["[Nintendo Wii]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "gamecube",
    name: "Nintendo GameCube",
    group: "nintendo",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=773",
    titleSearch: ["[GameCube]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "wiiu",
    name: "Nintendo Wii U",
    group: "nintendo",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=773",
    titleSearch: ["[Nintendo Wii U]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "ds",
    name: "Nintendo DS",
    group: "nintendo",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=774",
    titleSearch: ["[NDS]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "3ds",
    name: "Nintendo 3DS",
    group: "nintendo",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=774",
    titleSearch: ["[3DS]"],
    enabled: true,
    builtIn: true,
  },
  {
    id: "dreamcast",
    name: "Sega Dreamcast",
    group: "sega",
    baseUrl: "https://rutracker.org/forum/viewforum.php?f=968",
    titleSearch: ["[Dreamcast]"],
    enabled: true,
    builtIn: true,
  },
];

module.exports = {
  DEFAULT_CATEGORIES,
};
