/**
 * Torrent Worker IPC Message Protocol
 */

const WORKER_MESSAGES = {
  START_METADATA_FETCH: 'START_METADATA_FETCH',
  CANCEL_METADATA_FETCH: 'CANCEL_METADATA_FETCH',
  METADATA_RESULT: 'METADATA_RESULT',
  WORKER_READY: 'WORKER_READY',
  SHUTDOWN: 'SHUTDOWN',
};

module.exports = {
  WORKER_MESSAGES,
};
